### ISSUE TITLE
pos array from rtipsy can lead to confusion with wtipsy

### ISSUE THREAD

**Issue by bwkeller** [bwkeller/pytipsy#2]
The convenience array 'pos' can be altered without the 'x','y','z' arrays being updated.  Two arrays that ostensibly contain the same data can become out of sync with each other, leading to frustrating bugs.

**Comment by levineza** [comment]
That shouldn't be the case. They should point to the same memory. When I was doing testing I confirmed that no data was duplicated.

As seen below, modifying the 'pos' array for me does update 'x', 'y', and 'z' - and vise-versa.

In [4]: g['x'][0]
Out[4]: -0.2195582240819931

In [5]: g['pos'][0]
Out[5]: array([-0.21955822,  0.99319685, -0.91677362])

In [6]: g['pos'][0][0]
Out[6]: -0.2195582240819931

In [7]: g['pos'][0][0] = 2

In [8]: g['pos'][0][0]
Out[8]: 2.0

In [9]: g['x'][0]
Out[9]: 2.0

In [10]: g['x'][0] = 3.14

In [11]: g['x'][0]
Out[11]: 3.1400000000000001

In [12]: g['pos'][0][0]
Out[12]: 3.1400000000000001

Could you send me an example where it breaks? (they'll still act like python variables so if you make it point to something else then of course they will get out of snyc; but you should be able to in-place modify the elements fine ) Also, the change should not affect wtipsy at all. You don't need to make a 'pos' array at all when using wtipsy if you're creating an IC or saving data. The 'pos' and 'vel' arrays do allow for much easier analysis and cohesion with numpy functions.
